export const copy = {
  header: {
    renameDocument: 'Rename document',
    fileNameLabel: 'Document file name',
    privacyPill: 'Private by design',
    localOnly: 'local only',
    confirmedSuffix: 'confirmed',
    toReviewSuffix: 'to review',
    findingSingular: 'finding',
    findingPlural: 'findings',
    redo: 'Redo',
    export: 'Export',
    reset: 'Reset',
  },
  dock: {
    openReview: (pending: number) => `Open review sidebar (${pending} pending)`,
    closeReview: 'Close review sidebar',
    redo: 'Redo',
    enableSelect: 'Enable select mode',
    disableSelect: 'Disable select mode',
    enableDraw: 'Enable draw mode',
    disableDraw: 'Disable draw mode',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
  },
  sidebar: {
    reviewQueue: 'Review queue',
    removeFile: 'Remove',
    export: 'Export',
    watchWords: 'Watch for these words',
    addKeywordPlaceholder: 'Add a keyword…',
    noKeywords: 'None yet.',
    emptyTitle: 'Nothing in this view.',
    emptyDescription: 'Load a PDF to see detections, or adjust your filters.',
    confirmAllOnAll: (count: number) => `→ Confirm all ${count} on all pages`,
    unconfirmAllOnAll: (count: number) => `→ Unconfirm all ${count} on all pages`,
    confirmAllInGroup: (count: number) => `→ Confirm all ${count} in this group`,
    rejectAllInGroup: (count: number) => `→ Reject all ${count} in this group`,
    confirmAllShort: (count: number) => `confirm all ${count}`,
    rejectAllShort: (count: number) => `reject all ${count}`,
    confirmTooltip: 'Confirm (A)',
    unconfirmTooltip: 'Unconfirm (R)',
    removeTooltip: 'Remove',
  },
  dropzone: {
    eyebrow: 'STEP 01',
    headingLead: "Let's get your",
    headingAccent: 'PDF.',
    hint: 'Drag a document here or choose a file.',
    processing: 'Preparing your PDF locally',
    preparing: 'Getting your file ready…',
    warmingEngine: 'Starting local processing',
    release: 'Drop to start processing locally',
    drop: 'Drop your PDF here',
    browse: 'or click to browse',
    choose: 'Choose a PDF',
    fileLimit: 'PDF only · up to 25 MB · 30 pages',
    localOnly: 'Your file never leaves your device',
    trustTitle: 'Processing on your device',
    trustHeading: 'Your PDF is private and secure.',
    trustBody: 'We never upload your files anywhere.',
    trustStatus: 'Nothing is being uploaded',
    reassuranceBody: 'This happens entirely on your device. You stay in control.',
    footer: 'No uploads. No storage. Just private PDF redaction.',
    benefits: [
      {
        id: 'privacy',
        title: '100% Private',
        body: 'Your files never leave your device.',
      },
      {
        id: 'local',
        title: 'Fast & Local',
        body: 'All processing happens right in your browser.',
      },
      {
        id: 'account',
        title: 'No Sign Up',
        body: 'No account required. Just your PDF.',
      },
    ],
  },
  ocr: {
    eyebrow: 'Confirm OCR language',
    heading: 'We detected a language for OCR',
    body: 'Review the selected language before OCR starts. You can change it if the scan looks different.',
    fallbackHeading: 'Choose languages for PDF text',
    fallbackBody:
      'Due to the garbled text, no reliable language was detected. Pick the languages visible in this document to start fallback scanning.',
    note: 'Your document is not being uploaded anywhere. We are just getting additional context to improve accuracy.',
    cancel: 'Cancel',
    start: 'Continue',
  },
  confirmAllExport: {
    title: 'Nothing confirmed yet',
    body: 'No highlights are confirmed for export. Do you want to confirm all current markings, or cancel and keep reviewing first?',
    cancel: 'Cancel',
    confirm: 'Confirm all markings',
  },
  resetSession: {
    title: 'Reset session?',
    body: 'This clears the loaded PDF, detections, manual redactions, and review state for the current session.',
    cancel: 'Cancel',
    confirm: 'Reset session',
  },
  consent: {
    regionLabel: 'Cookie consent',
    eyebrow: 'Analytics consent',
    heading: 'Help us understand usage, not your documents.',
    body: 'We only use analytics to understand how many people use the site and which parts work well. Analytics starts with denied-by-default consent settings, and your PDFs never leave your computer.',
    decline: 'Decline',
    accept: 'Accept analytics',
  },
  manualToolbar: {
    confirm: 'Confirm manual highlight',
    dismiss: 'Discard manual highlight',
  },
} as const;
