export const copy = {
  header: {
    renameDocument: 'Rename document',
    fileNameLabel: 'Document file name',
    localOnly: 'local only',
    confirmedSuffix: 'confirmed',
    toReviewSuffix: 'to review',
    findingSingular: 'finding',
    findingPlural: 'findings',
    redo: 'Redo',
    export: 'Export',
    reset: 'Reset',
  },
  dock: {
    openReview: (pending: number) => `Open review sidebar (${pending} pending)`,
    closeReview: 'Close review sidebar',
    redo: 'Redo',
    enableSelect: 'Enable select mode',
    disableSelect: 'Disable select mode',
    enableDraw: 'Enable draw mode',
    disableDraw: 'Disable draw mode',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
  },
  sidebar: {
    reviewQueue: 'Review queue',
    removeFile: 'Remove file',
    export: 'Export',
    watchWords: 'Watch for these words',
    addKeywordPlaceholder: 'Add a keyword…',
    noKeywords: 'None yet.',
    emptyTitle: 'Nothing in this view.',
    emptyDescription: 'Load a PDF to see detections, or adjust your filters.',
    confirmAllOnAll: (count: number) => `→ Confirm all ${count} on all pages`,
    unconfirmAllOnAll: (count: number) => `→ Unconfirm all ${count} on all pages`,
    confirmAllInGroup: (count: number) => `→ Confirm all ${count} in this group`,
    rejectAllInGroup: (count: number) => `→ Reject all ${count} in this group`,
    confirmAllShort: (count: number) => `confirm all ${count}`,
    rejectAllShort: (count: number) => `reject all ${count}`,
    confirmTooltip: 'Confirm (A)',
    unconfirmTooltip: 'Unconfirm (R)',
    removeTooltip: 'Remove',
  },
  dropzone: {
    eyebrow: 'STEP 01 - DROP A DOCUMENT',
    headingLead: 'Start with a',
    headingAccent: 'PDF.',
    hint: 'Drag a document here or choose a file. Nothing leaves your browser.',
    processing: 'Processing your PDF…',
    preparing: 'Preparing document…',
    warmingEngine: 'Warming up engine…',
    release: 'Release to upload',
    drop: 'Drop your PDF here',
    browse: 'or click to browse',
    choose: 'Choose a PDF',
  },
  ocr: {
    eyebrow: 'Choose OCR languages',
    heading: 'This PDF needs a language hint before OCR',
    body: 'No searchable text was available for auto-detection. Pick the languages visible in this document, then start OCR.',
    note: 'Extra languages are fetched on demand and cached by your browser.',
    cancel: 'Cancel',
    start: 'Start OCR',
  },
  confirmAllExport: {
    title: 'Nothing confirmed yet',
    body: 'No highlights are confirmed for export. Do you want to confirm all current markings, or cancel and keep reviewing first?',
    cancel: 'Cancel',
    confirm: 'Confirm all markings',
  },
  resetSession: {
    title: 'Reset session?',
    body: 'This clears the loaded PDF, detections, manual redactions, and review state for the current session.',
    cancel: 'Cancel',
    confirm: 'Reset session',
  },
  consent: {
    regionLabel: 'Cookie consent',
    eyebrow: 'Analytics consent',
    heading: 'Help us understand usage, not your documents.',
    body: 'We only use analytics to understand how many people use the site and which parts work well. Analytics starts with denied-by-default consent settings, and your PDFs never leave your computer.',
    decline: 'Decline',
    accept: 'Accept analytics',
  },
  manualToolbar: {
    confirm: 'Confirm manual highlight',
    dismiss: 'Discard manual highlight',
  },
} as const;
